import { StyleSheet } from "react-native"
import { Colors } from "../../../../shared/theme/Colors"

const styles=StyleSheet.create({
    overlay:{
        flex:1,
        justifyContent:"flex-end",
        backgroundColor:"rgba(0,0,0,0.6)",
    },
    sheet:{
        backgroundColor:"#14171d",
        borderTopLeftRadius:24,
        borderTopRightRadius:24,
        paddingHorizontal:20,
        paddingTop:12,
        paddingBottom:28,
    },
    handle:{
        width:40,
        height:4,
        borderRadius:2,
        backgroundColor:"#333844",
        alignSelf:"center",
        marginBottom:16,
    },
    title:{
        color:Colors.white,
        fontSize:20,
        fontWeight:"bold",
        marginBottom:16,
    },
    segment:{
        flexDirection:"row",
        backgroundColor:"#1c1f26",
        borderRadius:14,
        padding:4,
        gap:4,
        marginBottom:20,
    },
    segmentBtn:{
        flex:1,
        paddingVertical:10,
        borderRadius:10,
        alignItems:"center",
    },
    segmentBtnExpenseActive:{
        backgroundColor:"#a5342a",
    },
    segmentBtnIncomeActive:{
        backgroundColor:Colors.success,
    },
    segmentText:{
        color:"#8b93a1",
        fontWeight:"bold",
        fontSize:14,
    },
    segmentTextActive:{
        color:Colors.white,
    },
    label:{
        color:"#8b93a1",
        fontSize:13,
        fontWeight:"600",
        marginBottom:10,
    },
    amountRow:{
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
        gap:8,
        marginBottom:20,
    },
    currency:{
        color:"#7a4a3a",
        fontSize:24,
        fontWeight:"bold",
    },
    amountInput:{
        color:Colors.white,
        fontSize:44,
        fontWeight:"bold",
        textAlign:"center",
        minWidth:60,
        padding:0,
    },
    chipRow:{
        flexDirection:"row",
        flexWrap:"wrap",
        gap:8,
        marginBottom:20,
    },
    chip:{
        paddingHorizontal:14,
        paddingVertical:10,
        borderRadius:14,
        backgroundColor:"#1c1f26",
    },
    chipActive:{
        backgroundColor:"#4f46e5",
    },
    chipText:{
        color:Colors.white,
        fontSize:13,
        fontWeight:"600",
    },
    chipTextActive:{
        color:Colors.white,
    },
    dateRow:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        backgroundColor:"#1c1f26",
        borderRadius:12,
        paddingHorizontal:14,
        paddingVertical:14,
        marginBottom:20,
    },
    dateText:{
        color:Colors.white,
        fontSize:14,
        fontWeight:"600",
    },
    noteInput:{
        backgroundColor:"#1c1f26",
        borderRadius:12,
        paddingHorizontal:14,
        paddingVertical:14,
        color:Colors.white,
        fontSize:14,
        marginBottom:20,
    },
    recurringRow:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        marginBottom:24,
        gap:12,
    },
    recurringText:{
        flex:1,
        gap:2,
    },
    recurringTitle:{
        color:Colors.white,
        fontSize:14,
        fontWeight:"bold",
    },
    recurringSubtitle:{
        color:"#5a6472",
        fontSize:12,
    },
    saveBtn:{
        backgroundColor:"#2a2f3a",
        borderRadius:14,
        paddingVertical:16,
        alignItems:"center",
    },
    saveBtnText:{
        color:Colors.white,
        fontSize:15,
        fontWeight:"bold",
    }
});
export default styles;
